<a href="https://colab.research.google.com/github/rgaguiar/recuperacao_endereco/blob/main/fake_database.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install -q Faker

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.9/1.9 MB 32.5 MB/s eta 0:00:00

In [2]:
import pandas as pd
import random
from faker import Faker

In [3]:
# Inicializar Faker com suporte ao português
fake = Faker("pt_BR")

In [97]:
# Função para gerar dados da tabela 'Clientes'
def criar_clientes(n=1000):
    genero = ["Masculino", "Feminino"]
    estado_civil = ["Solteiro", "Casado", "Divorciado", "Viúvo"]
    empregado = ["Sim", "Não"]
    nivel_educacao = ["Ensino Fundamental", "Ensino Médio", "Ensino Superior", "Pós-graduação"]

    clientes = []
    for i in range(1, n+1):
        clientes.append({
            "cliente_id": i,
            "nome": fake.name(),
            "data_nascimento": fake.date_of_birth(minimum_age=20),
            "email": fake.email(),
            "telefone": fake.phone_number(),
            "data_cadastro": fake.date_between(start_date="-1y", end_date="today"),
            "genero": random.choice(genero),
            "estado_civil": random.choice(estado_civil),
            "profissao": fake.job(),
            "empregado": random.choice(empregado),
            "renda_mensal": round(random.uniform(1000, 100000), 2),
            "numero_filhos": random.randint(0, 5),
            "nivel_educacao": random.choice(nivel_educacao),
            "endereco": fake.address(),
            "cidade": fake.city(),
            "estado": fake.state_abbr(),
            "cep": fake.postcode()
        })
    return pd.DataFrame(clientes)

clientes_df = criar_clientes()

clientes_df['data_nascimento'] = pd.to_datetime(clientes_df['data_nascimento'])
clientes_df['data_cadastro'] = pd.to_datetime(clientes_df['data_cadastro'])
clientes_df.info()
display(clientes_df)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 17 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   cliente_id       1000 non-null   int64
 1   nome             1000 non-null   object
 2   data_nascimento  1000 non-null   datetime64[ns]
 3   email            1000 non-null   object
 4   telefone         1000 non-null   object
 5   data_cadastro    1000 non-null   datetime64[ns]
 6   genero           1000 non-null   object
 7   estado_civil     1000 non-null   object
 8   profissao        1000 non-null   object
 9   empregado        1000 non-null   object
 10  renda_mensal     1000 non-null   float64
 11  numero_filhos    1000 non-null   int64
 12  nivel_educacao   1000 non-null   object
 13  endereco         1000 non-null   object
 14  cidade           1000 non-null   object
 15  estado           1000 non-null   object
 16  cep              1000 non-null   object
dtypes: datetime64[ns](2), float64(1), int64(2), object(12)
memory usage: 132.9+ KB

,cliente_id,nome,data_nascimento,email,telefone,data_cadastro,genero,estado_civil,profissao,empregado,renda_mensal,numero_filhos,nivel_educacao,endereco,cidade,estado,cep
0,1,Fernanda Barros,1947-01-09,araujobeatriz@example.com,21 7184 2676,2024-09-08,Masculino,Solteiro,Designer de jóia,Sim,30165.23,0,Ensino Médio,"Alameda Luiz Otávio Fernandes, 802\nBiquinhas\...",Mendes de Castro,BA,18926-761
1,2,Carolina Novais,1989-10-14,carvalhobrenda@example.com,(011) 1257-8317,2024-06-25,Feminino,Viúvo,Manobrista,Sim,19606.25,2,Pós-graduação,"Vila Maria Sophia Marques, 764\nVila Nova Cach...",da Conceição,SP,66655029
2,3,Srta. Ayla Albuquerque,1913-10-08,garaujo@example.net,+55 71 1154-3993,2024-08-09,Masculino,Viúvo,Vendedor,Não,14629.08,3,Ensino Médio,"Rodovia de Vieira, 988\nItatiaia\n51218328 Fer...",Pimenta do Oeste,AL,67811270
3,4,Stephany Câmara,1948-04-01,mleao@example.net,71 0224-9217,2024-08-13,Masculino,Casado,Pneumologista,Não,84948.96,3,Pós-graduação,"Distrito Arthur Martins, 9\nGuaratã\n28628161 ...",Albuquerque,CE,31734-399
4,5,Maria Cecília Martins,1936-03-05,adias@example.com,(021) 6711-8637,2025-01-05,Feminino,Casado,Acompanhante,Não,40101.56,3,Pós-graduação,"Trecho Ravi Souza, 58\nDiamante\n60962-271 Sou...",Costa,ES,46762599
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,996,Lucas Gabriel Pimenta,1980-03-11,diogocarvalho@example.org,(061) 1664 6554,2025-02-01,Masculino,Viúvo,Tecnólogo em recursos pesqueiros,Sim,72087.94,5,Ensino Médio,Conjunto de Moreira\nVila Barragem Santa Lúcia...,Farias,CE,63451342
996,997,Bianca Martins,1988-06-06,pedro-miguel75@example.org,51 8768 9463,2024-12-18,Feminino,Casado,Engenheiro cartográfico,Sim,28386.39,5,Ensino Fundamental,Trecho de Gonçalves\nOuro Preto\n84992972 Viei...,Freitas do Amparo,TO,44304-836
997,998,Enzo da Cunha,1991-08-13,anovais@example.net,(021) 8384 5925,2024-11-11,Masculino,Divorciado,Auxiliar de reprografia,Não,36003.18,1,Ensino Médio,"Conjunto Ana Pastor, 25\nSolar Do Barreiro\n58...",Fernandes das Pedras,TO,33031172
998,999,Esther Montenegro,1954-12-13,caleb94@example.com,(051) 3439-4068,2024-04-27,Feminino,Viúvo,Mergulhador,Não,79607.13,0,Pós-graduação,"Área de Novaes, 957\nMaria Tereza\n79897917 Te...",Montenegro Verde,MS,13609-027
999,1000,Dr. Luigi Moraes,1913-11-02,isabelafreitas@example.com,(011) 8419 8737,2024-11-21,Feminino,Viúvo,Balconista,Não,56150.54,0,Ensino Fundamental,"Lago de Monteiro, 14\nVera Cruz\n18206-739 Pin...",Vieira,MS,70223-304

In [98]:
clientes_df['profissao'].value_counts()

profissao
Cumim                                    6
Lutador de karatê                        6
Agente de defesa sanitária animal        5
Médico cirurgião                         5
Seringueiro                              5
                                        ..
Engenheiro de alimentos                  1
Tecnólogo em produção Sucroalcooleira    1
Tesoureiro                               1
Fotógrafo                                1
Balconista                               1
Name: count, Length: 559, dtype: int64

In [99]:
# Função para criar dados da tabela produtos
def criar_produtos(n=100):
    categorias = ["Casual", "Formal", "Semi-formal", "Criativo", "Esportivo"]
    tipos_de_roupas = [
    "Calça jeans",
    "Camiseta gola V",
    "Camisa social",
    "Jaqueta",
    "Vestido",
    "Blusa de frio",
    "Shorts",
    "Saia",
    "Macacão",
    "Blazer",
    "Camiseta regata",
    "Moletom",
    "Terno",
    "Polo",
    "Bermuda"
]
    produtos = []
    for i in range(1, n+1):
        nome_produto = random.choice(tipos_de_roupas)
        produtos.append({
            "produto_id": i,
            "nome": random.choice(tipos_de_roupas),
            "categoria": random.choice(categorias),
            "preco_unitario": round(random.uniform(10, 2000), 2),
            "estoque_atual": random.randint(0, 500)
        })
    return pd.DataFrame(produtos)

produtos_df = criar_produtos(5)
produtos_df

   produto_id             nome  categoria  preco_unitario  estoque_atual
0           1    Camisa social  Esportivo          895.56            368
1           2             Polo  Esportivo          714.87            252
2           3           Blazer  Esportivo          523.82            467
3           4             Polo     Formal          428.50            219
4           5  Camiseta gola V     Casual          123.36            467

In [100]:
# Função para gerar dados da tabela 'Lojas'
def criar_lojas(n=10):
    lojas = []
    for i in range(1, n+1):
        lojas.append({
            "loja_id": i,
            "nome": f"Loja {i}",
            "endereco": fake.address(),
            "cidade": fake.city(),
            "estado": fake.state_abbr()
        })
    return pd.DataFrame(lojas)
lojas_df = criar_lojas(5)
lojas_df

,loja_id,nome,endereco,cidade,estado
0,1,Loja 1,"Rua de Alves, 88\nSanta Monica\n16909-915 Albu...",Moraes,SP
1,2,Loja 2,"Rodovia de Barros, 91\nProvidencia\n95235-219 ...",Siqueira da Serra,SP
2,3,Loja 3,"Ladeira Luana Machado, 2\nVila Madre Gertrudes...",Ribeiro do Sul,MG
3,4,Loja 4,"Conjunto Luiz Gustavo Araújo, 2\nErmelinda\n47...",Sousa,PB
4,5,Loja 5,"Setor Pires, 99\nVila Do Pombal\n33336-922 Sou...",Castro,AM

In [101]:
# Função para gerar dados da tabela 'Colaboradores'
def criar_colaboradores(n=50):
    cargos = ["Estagiário", "Vendedor Junior", "Vendedor Pleno", "Vendedor Senior", "Gerente"]
    colaboradores = []
    for i in range(1, n+1):
        loja = random.choice(lojas_df["loja_id"])
        colaboradores.append({
            "colaborador_id": i,
            "loja_id": loja,
            "nome": fake.name(),
            "cargo": random.choice(cargos),
            "data_admissao": fake.date_between(start_date="-1y", end_date="today")

        })

    # Definir os salários padrão para cada cargo

    return pd.DataFrame(colaboradores)

colaboradores_df = criar_colaboradores(50)

salarios_por_cargo = {
    "Estagiário": 1000.00,
    "Vendedor Junior": 1500.00,
    "Vendedor Pleno": 2500.00,
    "Vendedor Senior": 4000.00,
    "Gerente": 6000.00
}

# Atualizar os salários com base no cargo

colaboradores_df['salario'] = colaboradores_df['cargo'].map(salarios_por_cargo)
colaboradores_df['data_admissao'] = pd.to_datetime(colaboradores_df['data_admissao'])
display(colaboradores_df.head())
colaboradores_df.info()

,colaborador_id,loja_id,nome,cargo,data_admissao,salario
0,1,4,Maria Cecília da Paz,Vendedor Junior,2024-07-15,1500.0
1,2,2,Guilherme das Neves,Estagiário,2024-03-16,1000.0
2,3,5,Eduarda Vieira,Gerente,2024-12-26,6000.0
3,4,3,Maria Luísa Farias,Estagiário,2025-01-17,1000.0
4,5,4,Diego Vargas,Vendedor Junior,2024-02-11,1500.0

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   colaborador_id  50 non-null     int64
 1   loja_id         50 non-null     int64
 2   nome            50 non-null     object
 3   cargo           50 non-null     object
 4   data_admissao   50 non-null     datetime64[ns]
 5   salario         50 non-null     float64
dtypes: datetime64[ns](1), float64(1), int64(2), object(2)
memory usage: 2.5+ KB

In [102]:
# Função para gerar dados da tabela 'Vendas'
def criar_vendas(clientes_df, colaboradores_df, lojas_df, produtos_df, n=100000):
    vendas = []
    for i in range(1, n+1):
        cliente = random.choice(clientes_df["cliente_id"])
        vendedor = random.choice(colaboradores_df["colaborador_id"])
        loja = random.choice(lojas_df["loja_id"])
        produto = random.choice(produtos_df["produto_id"])
        quantidade = random.randint(1, 10)
        preco_unitario = produtos_df.loc[produtos_df["produto_id"] == produto, "preco_unitario"].values[0]
        vendas.append({
            "venda_id": i,
            "cliente_id": cliente,
            "vendedor_id": vendedor,
            "loja_id": loja,
            "produto_id": produto,
            "quantidade": quantidade,
            "preco_total": round(preco_unitario * quantidade, 2),
            "data_venda": fake.date_between(start_date="-1y", end_date="today")
        })
    return pd.DataFrame(vendas)

vendas_df = criar_vendas(clientes_df, colaboradores_df, lojas_df, produtos_df, n=100000)

vendas_df["data_venda"] = pd.to_datetime(vendas_df["data_venda"])
vendas_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   venda_id     100000 non-null  int64
 1   cliente_id   100000 non-null  int64
 2   vendedor_id  100000 non-null  int64
 3   loja_id      100000 non-null  int64
 4   produto_id   100000 non-null  int64
 5   quantidade   100000 non-null  int64
 6   preco_total  100000 non-null  float64
 7   data_venda   100000 non-null  datetime64[ns]
dtypes: datetime64[ns](1), float64(1), int64(6)
memory usage: 6.1 MB

In [103]:
# # Geração dos dados
# clientes_df = criar_clientes(n=50)
# colaboradores_df = criar_colaboradores(n=20)
# produtos_df = criar_produtos(n=100)
# lojas_df = criar_lojas(n=10)
# vendas_df = criar_vendas(clientes_df, colaboradores_df,  lojas_df, produtos_df, n=200)

In [104]:
colaboradores_df

,colaborador_id,loja_id,nome,cargo,data_admissao,salario
0,1,4,Maria Cecília da Paz,Vendedor Junior,2024-07-15,1500.0
1,2,2,Guilherme das Neves,Estagiário,2024-03-16,1000.0
2,3,5,Eduarda Vieira,Gerente,2024-12-26,6000.0
3,4,3,Maria Luísa Farias,Estagiário,2025-01-17,1000.0
4,5,4,Diego Vargas,Vendedor Junior,2024-02-11,1500.0
5,6,4,Leandro Rocha,Estagiário,2024-03-07,1000.0
6,7,3,Arthur Gabriel da Costa,Vendedor Pleno,2024-12-24,2500.0
7,8,4,Milena da Conceição,Estagiário,2024-09-14,1000.0
8,9,3,Isabelly Mendes,Estagiário,2024-03-02,1000.0
9,10,3,Levi Campos,Vendedor Senior,2024-04-20,4000.0
10,11,1,Maria Alice Machado,Gerente,2024-02-19,6000.0
11,12,5,Sr. Theodoro Abreu,Gerente,2024-09-25,6000.0
12,13,2,Davi Luiz Sá,Estagiário,2024-08-24,1000.0
13,14,1,Lucca Sousa,Vendedor Pleno,2025-01-22,2500.0
14,15,5,João Pedro Pacheco,Vendedor Pleno,2024-03-20,2500.0
15,16,3,Felipe Ramos,Estagiário,2024-02-23,1000.0
16,17,4,Maria Alice Gonçalves,Estagiário,2024-12-17,1000.0
17,18,3,Alice Vargas,Estagiário,2024-05-24,1000.0
18,19,3,Sr. João Miguel Nunes,Estagiário,2024-07-17,1000.0
19,20,2,Ana Sophia Aragão,Vendedor Junior,2024-05-13,1500.0
20,21,1,Mathias Cavalcante,Estagiário,2024-09-22,1000.0
21,22,3,Dr. Henry Cunha,Vendedor Pleno,2025-02-01,2500.0
22,23,4,Alexia Lima,Gerente,2024-02-22,6000.0
23,24,1,Arthur Vasconcelos,Vendedor Senior,2024-06-25,4000.0
24,25,3,Srta. Hellena Costela,Estagiário,2025-01-06,1000.0
25,26,3,Ester Costa,Vendedor Junior,2024-05-20,1500.0
26,27,1,Srta. Yasmin Cunha,Vendedor Pleno,2024-07-06,2500.0
27,28,1,Dra. Rebeca Moraes,Gerente,2024-04-09,6000.0
28,29,2,Enzo Gabriel Cassiano,Vendedor Pleno,2025-01-17,2500.0
29,30,5,Juan Moura,Vendedor Pleno,2024-12-30,2500.0
30,31,1,Daniela Brito,Vendedor Pleno,2025-01-11,2500.0
31,32,3,Henrique Camargo,Vendedor Junior,2024-04-19,1500.0
32,33,5,Jade Martins,Vendedor Pleno,2024-04-10,2500.0
33,34,3,Samuel Barros,Gerente,2024-07-04,6000.0
34,35,3,Davi Costa,Vendedor Pleno,2024-04-20,2500.0
35,36,1,Cauê da Cruz,Vendedor Senior,2024-04-24,4000.0
36,37,1,Nathan Vieira,Estagiário,2024-06-03,1000.0
37,38,3,Maria Luísa Novaes,Vendedor Pleno,2024-03-25,2500.0
38,39,3,Lucas Melo,Vendedor Senior,2024-12-29,4000.0
39,40,2,João Felipe das Neves,Vendedor Pleno,2024-12-17,2500.0
40,41,5,Luigi Rodrigues,Vendedor Senior,2024-09-15,4000.0
41,42,5,Josué Rios,Gerente,2024-11-13,6000.0
42,43,5,Dra. Maria Clara da Conceição,Vendedor Pleno,2024-04-17,2500.0
43,44,2,Renan Nunes,Estagiário,2024-04-06,1000.0
44,45,3,João Guilherme Gonçalves,Estagiário,2024-02-19,1000.0
45,46,4,Dra. Luara Guerra,Vendedor Pleno,2024-07-17,2500.0
46,47,4,Thales Mendonça,Gerente,2024-07-20,6000.0
47,48,3,Clarice da Costa,Estagiário,2024-04-19,1000.0
48,49,4,Davi Miguel Fonseca,Vendedor Pleno,2024-08-20,2500.0
49,50,4,José Miguel Camargo,Vendedor Senior,2024-06-21,4000.0

In [105]:
# Salvando os dados em CSVs
clientes_df.to_csv("clientes.csv", index=False)
colaboradores_df.to_csv("colaboradores.csv", index=False)
produtos_df.to_csv("produtos.csv", index=False)
lojas_df.to_csv("lojas.csv", index=False)
vendas_df.to_csv("vendas.csv", index=False)

print("Dados sintéticos gerados e salvos em arquivos CSV.")

Dados sintéticos gerados e salvos em arquivos CSV.

In [106]:
colaboradores_df

,colaborador_id,loja_id,nome,cargo,data_admissao,salario
0,1,4,Maria Cecília da Paz,Vendedor Junior,2024-07-15,1500.0
1,2,2,Guilherme das Neves,Estagiário,2024-03-16,1000.0
2,3,5,Eduarda Vieira,Gerente,2024-12-26,6000.0
3,4,3,Maria Luísa Farias,Estagiário,2025-01-17,1000.0
4,5,4,Diego Vargas,Vendedor Junior,2024-02-11,1500.0
5,6,4,Leandro Rocha,Estagiário,2024-03-07,1000.0
6,7,3,Arthur Gabriel da Costa,Vendedor Pleno,2024-12-24,2500.0
7,8,4,Milena da Conceição,Estagiário,2024-09-14,1000.0
8,9,3,Isabelly Mendes,Estagiário,2024-03-02,1000.0
9,10,3,Levi Campos,Vendedor Senior,2024-04-20,4000.0
10,11,1,Maria Alice Machado,Gerente,2024-02-19,6000.0
11,12,5,Sr. Theodoro Abreu,Gerente,2024-09-25,6000.0
12,13,2,Davi Luiz Sá,Estagiário,2024-08-24,1000.0
13,14,1,Lucca Sousa,Vendedor Pleno,2025-01-22,2500.0
14,15,5,João Pedro Pacheco,Vendedor Pleno,2024-03-20,2500.0
15,16,3,Felipe Ramos,Estagiário,2024-02-23,1000.0
16,17,4,Maria Alice Gonçalves,Estagiário,2024-12-17,1000.0
17,18,3,Alice Vargas,Estagiário,2024-05-24,1000.0
18,19,3,Sr. João Miguel Nunes,Estagiário,2024-07-17,1000.0
19,20,2,Ana Sophia Aragão,Vendedor Junior,2024-05-13,1500.0
20,21,1,Mathias Cavalcante,Estagiário,2024-09-22,1000.0
21,22,3,Dr. Henry Cunha,Vendedor Pleno,2025-02-01,2500.0
22,23,4,Alexia Lima,Gerente,2024-02-22,6000.0
23,24,1,Arthur Vasconcelos,Vendedor Senior,2024-06-25,4000.0
24,25,3,Srta. Hellena Costela,Estagiário,2025-01-06,1000.0
25,26,3,Ester Costa,Vendedor Junior,2024-05-20,1500.0
26,27,1,Srta. Yasmin Cunha,Vendedor Pleno,2024-07-06,2500.0
27,28,1,Dra. Rebeca Moraes,Gerente,2024-04-09,6000.0
28,29,2,Enzo Gabriel Cassiano,Vendedor Pleno,2025-01-17,2500.0
29,30,5,Juan Moura,Vendedor Pleno,2024-12-30,2500.0
30,31,1,Daniela Brito,Vendedor Pleno,2025-01-11,2500.0
31,32,3,Henrique Camargo,Vendedor Junior,2024-04-19,1500.0
32,33,5,Jade Martins,Vendedor Pleno,2024-04-10,2500.0
33,34,3,Samuel Barros,Gerente,2024-07-04,6000.0
34,35,3,Davi Costa,Vendedor Pleno,2024-04-20,2500.0
35,36,1,Cauê da Cruz,Vendedor Senior,2024-04-24,4000.0
36,37,1,Nathan Vieira,Estagiário,2024-06-03,1000.0
37,38,3,Maria Luísa Novaes,Vendedor Pleno,2024-03-25,2500.0
38,39,3,Lucas Melo,Vendedor Senior,2024-12-29,4000.0
39,40,2,João Felipe das Neves,Vendedor Pleno,2024-12-17,2500.0
40,41,5,Luigi Rodrigues,Vendedor Senior,2024-09-15,4000.0
41,42,5,Josué Rios,Gerente,2024-11-13,6000.0
42,43,5,Dra. Maria Clara da Conceição,Vendedor Pleno,2024-04-17,2500.0
43,44,2,Renan Nunes,Estagiário,2024-04-06,1000.0
44,45,3,João Guilherme Gonçalves,Estagiário,2024-02-19,1000.0
45,46,4,Dra. Luara Guerra,Vendedor Pleno,2024-07-17,2500.0
46,47,4,Thales Mendonça,Gerente,2024-07-20,6000.0
47,48,3,Clarice da Costa,Estagiário,2024-04-19,1000.0
48,49,4,Davi Miguel Fonseca,Vendedor Pleno,2024-08-20,2500.0
49,50,4,José Miguel Camargo,Vendedor Senior,2024-06-21,4000.0